#!/bin/bash
# Call LaTeXML on the input file 'x'
# Generate x.omdoc and x.mmt
# If X does not contain any MMT file
# Only x.omdoc is generated

########################################
basename=$1
preamble=pre.tex
postamble=post.tex
etcdir=../../../sTeX/sty/etc/
xsldir=../../lib/LaTeXML/resources/XSLT/
########################################

# Clean up existing files
if [ ! -f $preamble ] || [ ! -f $postamble ]
   then
	echo "Preamble or postamble not found!"
    	exit 1
fi

if [ -f $1.omdoc ]
   then
	rm $1.omdoc
fi

if [ -f $1.mmt ]
   then
	rm $1.mmt
fi

# Generate x.omdoc
latexmlc --profile stex-omdoc-modules  --path $etcdir --preamble $preamble --postamble $postamble $1 >> $basename.omdoc

# Extract MMT stuff from x.omdoc
xsltproc  --stringparam fileName $basename --output $basename.mmt $xsldir/mmt.xsl  $basename.omdoc 
perl replace.pl $basename.mmt



